const SOCKET_COMANDS = {
    USERS: {
        LOGIN: 'USERS_LOGIN',
        LOGOUT: 'USERS_LOGOUT',
        GET_ONLINE: 'USERS_GET_ONLINE'
    },
    ADMIN: {
        LOGIN: 'ADMIN_LOGIN',
        LOGOUT: 'ADMIN_LOGOUT',
    },
    GAME: {
        CREATE_SESSION: 'GAME_CREATE_SESSION',
        PAUSE_SESSION: 'GAME_PAUSE_SESSION',
        CONTINUE_SESSION: 'GAME_CONTINUE_SESSION',
        UPDATE_SESSION: 'GAME_UPDATE_SESSION',
        GET_PLAYERS: 'GAME_GET_PLAYERS'
    },
}

export default SOCKET_COMANDS;